# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KullaniciArayuzu.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import veri

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 811, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Uruninsert = QtWidgets.QPushButton(self.tab)
        self.Uruninsert.setGeometry(QtCore.QRect(170, 40, 111, 51))
        self.Uruninsert.setObjectName("Uruninsert")
        self.Bileseninsert = QtWidgets.QPushButton(self.tab)
        self.Bileseninsert.setGeometry(QtCore.QRect(560, 30, 111, 51))
        self.Bileseninsert.setObjectName("Bileseninsert")
        self.urunstok = QtWidgets.QLineEdit(self.tab)
        self.urunstok.setGeometry(QtCore.QRect(30, 50, 121, 31))
        self.urunstok.setObjectName("urunstok")
        self.urunad = QtWidgets.QLineEdit(self.tab)
        self.urunad.setGeometry(QtCore.QRect(30, 20, 121, 31))
        self.urunad.setObjectName("urunad")
        self.urunad2 = QtWidgets.QLineEdit(self.tab)
        self.urunad2.setGeometry(QtCore.QRect(420, 20, 121, 31))
        self.urunad2.setObjectName("urunad2")
        self.uruntarih = QtWidgets.QLineEdit(self.tab)
        self.uruntarih.setGeometry(QtCore.QRect(30, 80, 121, 31))
        self.uruntarih.setObjectName("uruntarih")
        self.urunraf = QtWidgets.QLineEdit(self.tab)
        self.urunraf.setGeometry(QtCore.QRect(30, 110, 121, 31))
        self.urunraf.setObjectName("urunraf")
        self.bilesenad = QtWidgets.QLineEdit(self.tab)
        self.bilesenad.setGeometry(QtCore.QRect(420, 50, 121, 31))
        self.bilesenad.setObjectName("bilesenad")
        self.bilesenmiktar = QtWidgets.QLineEdit(self.tab)
        self.bilesenmiktar.setGeometry(QtCore.QRect(420, 80, 121, 31))
        self.bilesenmiktar.setObjectName("bilesenmiktar")
        self.UrunSelectAll = QtWidgets.QPushButton(self.tab)
        self.UrunSelectAll.setGeometry(QtCore.QRect(170, 90, 111, 31))
        self.UrunSelectAll.setObjectName("UrunSelectAll")
        self.UrunSelect = QtWidgets.QPushButton(self.tab)
        self.UrunSelect.setGeometry(QtCore.QRect(230, 150, 75, 23))
        self.UrunSelect.setObjectName("UrunSelect")
        self.urunselect = QtWidgets.QLineEdit(self.tab)
        self.urunselect.setGeometry(QtCore.QRect(30, 150, 191, 20))
        self.urunselect.setObjectName("urunselect")
        self.BilesenSelectAll = QtWidgets.QPushButton(self.tab)
        self.BilesenSelectAll.setGeometry(QtCore.QRect(560, 80, 111, 31))
        self.BilesenSelectAll.setObjectName("BilesenSelectAll")
        self.bilesenselect = QtWidgets.QLineEdit(self.tab)
        self.bilesenselect.setGeometry(QtCore.QRect(420, 150, 191, 20))
        self.bilesenselect.setObjectName("bilesenselect")
        self.BilesenSelect = QtWidgets.QPushButton(self.tab)
        self.BilesenSelect.setGeometry(QtCore.QRect(620, 150, 75, 23))
        self.BilesenSelect.setObjectName("BilesenSelect")
        self.list10 = QtWidgets.QListWidget(self.tab)
        self.list10.setGeometry(QtCore.QRect(30, 220, 71, 192))
        self.list10.setObjectName("list10")
        self.list12 = QtWidgets.QListWidget(self.tab)
        self.list12.setGeometry(QtCore.QRect(170, 220, 71, 192))
        self.list12.setObjectName("list12")
        self.list13 = QtWidgets.QListWidget(self.tab)
        self.list13.setGeometry(QtCore.QRect(240, 220, 71, 192))
        self.list13.setObjectName("list13")
        self.list20 = QtWidgets.QListWidget(self.tab)
        self.list20.setGeometry(QtCore.QRect(460, 220, 71, 192))
        self.list20.setObjectName("list20")
        self.list11 = QtWidgets.QListWidget(self.tab)
        self.list11.setGeometry(QtCore.QRect(100, 220, 71, 192))
        self.list11.setObjectName("list11")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(100, 200, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(310, 200, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(170, 200, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(240, 200, 71, 21))
        self.label_4.setObjectName("label_4")
        self.list21 = QtWidgets.QListWidget(self.tab)
        self.list21.setGeometry(QtCore.QRect(530, 220, 71, 192))
        self.list21.setObjectName("list21")
        self.list22 = QtWidgets.QListWidget(self.tab)
        self.list22.setGeometry(QtCore.QRect(600, 220, 71, 192))
        self.list22.setObjectName("list22")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(460, 200, 71, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(530, 200, 71, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(600, 200, 71, 21))
        self.label_7.setObjectName("label_7")
        self.hataEkrani = QtWidgets.QLabel(self.tab)
        self.hataEkrani.setGeometry(QtCore.QRect(40, 450, 441, 51))
        self.hataEkrani.setText("")
        self.hataEkrani.setObjectName("hataEkrani")
        self.list13_2 = QtWidgets.QListWidget(self.tab)
        self.list13_2.setGeometry(QtCore.QRect(310, 220, 71, 192))
        self.list13_2.setObjectName("list13_2")
        self.label_38 = QtWidgets.QLabel(self.tab)
        self.label_38.setGeometry(QtCore.QRect(30, 200, 71, 21))
        self.label_38.setObjectName("label_38")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tedarikciFad = QtWidgets.QLineEdit(self.tab_3)
        self.tedarikciFad.setGeometry(QtCore.QRect(30, 30, 131, 31))
        self.tedarikciFad.setObjectName("tedarikciFad")
        self.tedarikciFulke = QtWidgets.QLineEdit(self.tab_3)
        self.tedarikciFulke.setGeometry(QtCore.QRect(30, 60, 131, 31))
        self.tedarikciFulke.setObjectName("tedarikciFulke")
        self.tedarikciFsehir = QtWidgets.QLineEdit(self.tab_3)
        self.tedarikciFsehir.setGeometry(QtCore.QRect(30, 90, 131, 31))
        self.tedarikciFsehir.setObjectName("tedarikciFsehir")
        self.Tedarikcifirmainsert = QtWidgets.QPushButton(self.tab_3)
        self.Tedarikcifirmainsert.setGeometry(QtCore.QRect(180, 40, 111, 51))
        self.Tedarikcifirmainsert.setObjectName("Tedarikcifirmainsert")
        self.tedarikcifirmaselectall = QtWidgets.QPushButton(self.tab_3)
        self.tedarikcifirmaselectall.setGeometry(QtCore.QRect(180, 90, 111, 31))
        self.tedarikcifirmaselectall.setObjectName("tedarikcifirmaselectall")
        self.tedarikciFselect = QtWidgets.QLineEdit(self.tab_3)
        self.tedarikciFselect.setGeometry(QtCore.QRect(30, 180, 191, 20))
        self.tedarikciFselect.setObjectName("tedarikciFselect")
        self.tedarikcifirmaselect = QtWidgets.QPushButton(self.tab_3)
        self.tedarikcifirmaselect.setGeometry(QtCore.QRect(230, 180, 75, 23))
        self.tedarikcifirmaselect.setObjectName("tedarikcifirmaselect")
        self.List33 = QtWidgets.QListWidget(self.tab_3)
        self.List33.setGeometry(QtCore.QRect(240, 240, 71, 192))
        self.List33.setObjectName("List33")
        self.List32 = QtWidgets.QListWidget(self.tab_3)
        self.List32.setGeometry(QtCore.QRect(170, 240, 71, 192))
        self.List32.setObjectName("List32")
        self.List31 = QtWidgets.QListWidget(self.tab_3)
        self.List31.setGeometry(QtCore.QRect(100, 240, 71, 192))
        self.List31.setObjectName("List31")
        self.List30 = QtWidgets.QListWidget(self.tab_3)
        self.List30.setGeometry(QtCore.QRect(30, 240, 71, 192))
        self.List30.setObjectName("List30")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(30, 220, 71, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(100, 220, 71, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(170, 220, 71, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(240, 220, 71, 21))
        self.label_11.setObjectName("label_11")
        self.tedarikciAd = QtWidgets.QLineEdit(self.tab_3)
        self.tedarikciAd.setGeometry(QtCore.QRect(380, 20, 131, 31))
        self.tedarikciAd.setObjectName("tedarikciAd")
        self.TedarikciMiktar = QtWidgets.QLineEdit(self.tab_3)
        self.TedarikciMiktar.setGeometry(QtCore.QRect(380, 50, 131, 31))
        self.TedarikciMiktar.setObjectName("TedarikciMiktar")
        self.TedarikciUretim = QtWidgets.QLineEdit(self.tab_3)
        self.TedarikciUretim.setGeometry(QtCore.QRect(380, 80, 131, 31))
        self.TedarikciUretim.setObjectName("TedarikciUretim")
        self.TedarikciRafomru = QtWidgets.QLineEdit(self.tab_3)
        self.TedarikciRafomru.setGeometry(QtCore.QRect(380, 110, 131, 31))
        self.TedarikciRafomru.setObjectName("TedarikciRafomru")
        self.TedarikciSatis = QtWidgets.QLineEdit(self.tab_3)
        self.TedarikciSatis.setGeometry(QtCore.QRect(380, 140, 131, 31))
        self.TedarikciSatis.setObjectName("TedarikciSatis")
        self.List44 = QtWidgets.QListWidget(self.tab_3)
        self.List44.setGeometry(QtCore.QRect(620, 240, 71, 192))
        self.List44.setObjectName("List44")
        self.List43 = QtWidgets.QListWidget(self.tab_3)
        self.List43.setGeometry(QtCore.QRect(550, 240, 71, 192))
        self.List43.setObjectName("List43")
        self.List42 = QtWidgets.QListWidget(self.tab_3)
        self.List42.setGeometry(QtCore.QRect(480, 240, 71, 192))
        self.List42.setObjectName("List42")
        self.List41 = QtWidgets.QListWidget(self.tab_3)
        self.List41.setGeometry(QtCore.QRect(410, 240, 71, 192))
        self.List41.setObjectName("List41")
        self.List40 = QtWidgets.QListWidget(self.tab_3)
        self.List40.setGeometry(QtCore.QRect(340, 240, 71, 192))
        self.List40.setObjectName("List40")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(690, 220, 71, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(620, 220, 71, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(550, 220, 71, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(480, 220, 71, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(410, 220, 71, 21))
        self.label_16.setObjectName("label_16")
        self.tedarikciinsert = QtWidgets.QPushButton(self.tab_3)
        self.tedarikciinsert.setGeometry(QtCore.QRect(530, 40, 111, 51))
        self.tedarikciinsert.setObjectName("tedarikciinsert")
        self.tedarikciselectall = QtWidgets.QPushButton(self.tab_3)
        self.tedarikciselectall.setGeometry(QtCore.QRect(530, 90, 111, 31))
        self.tedarikciselectall.setObjectName("tedarikciselectall")
        self.tedarikciselect = QtWidgets.QPushButton(self.tab_3)
        self.tedarikciselect.setGeometry(QtCore.QRect(580, 180, 75, 23))
        self.tedarikciselect.setObjectName("tedarikciselect")
        self.TedarikciSelect = QtWidgets.QLineEdit(self.tab_3)
        self.TedarikciSelect.setGeometry(QtCore.QRect(380, 180, 191, 20))
        self.TedarikciSelect.setObjectName("TedarikciSelect")
        self.List45 = QtWidgets.QListWidget(self.tab_3)
        self.List45.setGeometry(QtCore.QRect(690, 240, 71, 192))
        self.List45.setObjectName("List45")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(340, 220, 71, 21))
        self.label_23.setObjectName("label_23")
        self.TedarikiFirmaID = QtWidgets.QLineEdit(self.tab_3)
        self.TedarikiFirmaID.setGeometry(QtCore.QRect(510, 140, 131, 31))
        self.TedarikiFirmaID.setObjectName("TedarikiFirmaID")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.musteriAd = QtWidgets.QLineEdit(self.tab_2)
        self.musteriAd.setGeometry(QtCore.QRect(30, 70, 131, 31))
        self.musteriAd.setObjectName("musteriAd")
        self.musteriSelectAll = QtWidgets.QPushButton(self.tab_2)
        self.musteriSelectAll.setGeometry(QtCore.QRect(170, 90, 111, 31))
        self.musteriSelectAll.setObjectName("musteriSelectAll")
        self.musteriSelect = QtWidgets.QPushButton(self.tab_2)
        self.musteriSelect.setGeometry(QtCore.QRect(220, 180, 75, 23))
        self.musteriSelect.setObjectName("musteriSelect")
        self.musteriArama = QtWidgets.QLineEdit(self.tab_2)
        self.musteriArama.setGeometry(QtCore.QRect(20, 180, 191, 20))
        self.musteriArama.setObjectName("musteriArama")
        self.list50 = QtWidgets.QListWidget(self.tab_2)
        self.list50.setGeometry(QtCore.QRect(60, 230, 71, 192))
        self.list50.setObjectName("list50")
        self.list51 = QtWidgets.QListWidget(self.tab_2)
        self.list51.setGeometry(QtCore.QRect(130, 230, 71, 192))
        self.list51.setObjectName("list51")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(130, 210, 71, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(60, 210, 71, 21))
        self.label_18.setObjectName("label_18")
        self.siparisAdres = QtWidgets.QLineEdit(self.tab_2)
        self.siparisAdres.setGeometry(QtCore.QRect(380, 70, 131, 31))
        self.siparisAdres.setObjectName("siparisAdres")
        self.siparisID = QtWidgets.QLineEdit(self.tab_2)
        self.siparisID.setGeometry(QtCore.QRect(380, 40, 131, 31))
        self.siparisID.setObjectName("siparisID")
        self.siparisUrun = QtWidgets.QLineEdit(self.tab_2)
        self.siparisUrun.setGeometry(QtCore.QRect(380, 100, 131, 31))
        self.siparisUrun.setObjectName("siparisUrun")
        self.siparisMiktar = QtWidgets.QLineEdit(self.tab_2)
        self.siparisMiktar.setGeometry(QtCore.QRect(380, 130, 131, 31))
        self.siparisMiktar.setObjectName("siparisMiktar")
        self.musteriInsert = QtWidgets.QPushButton(self.tab_2)
        self.musteriInsert.setGeometry(QtCore.QRect(170, 40, 111, 51))
        self.musteriInsert.setObjectName("musteriInsert")
        self.siparisInsert = QtWidgets.QPushButton(self.tab_2)
        self.siparisInsert.setGeometry(QtCore.QRect(520, 40, 111, 51))
        self.siparisInsert.setObjectName("siparisInsert")
        self.siparisSelectAll = QtWidgets.QPushButton(self.tab_2)
        self.siparisSelectAll.setGeometry(QtCore.QRect(520, 90, 111, 31))
        self.siparisSelectAll.setObjectName("siparisSelectAll")
        self.siparisArama = QtWidgets.QLineEdit(self.tab_2)
        self.siparisArama.setGeometry(QtCore.QRect(380, 180, 191, 20))
        self.siparisArama.setObjectName("siparisArama")
        self.siparisSelect = QtWidgets.QPushButton(self.tab_2)
        self.siparisSelect.setGeometry(QtCore.QRect(580, 180, 75, 23))
        self.siparisSelect.setObjectName("siparisSelect")
        self.list64 = QtWidgets.QListWidget(self.tab_2)
        self.list64.setGeometry(QtCore.QRect(620, 230, 71, 192))
        self.list64.setObjectName("list64")
        self.list63 = QtWidgets.QListWidget(self.tab_2)
        self.list63.setGeometry(QtCore.QRect(550, 230, 71, 192))
        self.list63.setObjectName("list63")
        self.list62 = QtWidgets.QListWidget(self.tab_2)
        self.list62.setGeometry(QtCore.QRect(450, 230, 101, 192))
        self.list62.setObjectName("list62")
        self.list61 = QtWidgets.QListWidget(self.tab_2)
        self.list61.setGeometry(QtCore.QRect(380, 230, 71, 192))
        self.list61.setObjectName("list61")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(380, 210, 71, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(470, 210, 71, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(550, 210, 71, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(620, 210, 71, 16))
        self.label_22.setObjectName("label_22")
        self.hataEkrani2 = QtWidgets.QLabel(self.tab_2)
        self.hataEkrani2.setGeometry(QtCore.QRect(60, 450, 501, 51))
        self.hataEkrani2.setText("")
        self.hataEkrani2.setObjectName("hataEkrani2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.hammaddeAlis = QtWidgets.QLineEdit(self.tab_4)
        self.hammaddeAlis.setGeometry(QtCore.QRect(20, 20, 251, 41))
        self.hammaddeAlis.setObjectName("hammaddeAlis")
        self.search = QtWidgets.QPushButton(self.tab_4)
        self.search.setGeometry(QtCore.QRect(280, 40, 101, 51))
        self.search.setObjectName("search")
        self.list72 = QtWidgets.QListWidget(self.tab_4)
        self.list72.setGeometry(QtCore.QRect(160, 130, 71, 192))
        self.list72.setObjectName("list72")
        self.list71 = QtWidgets.QListWidget(self.tab_4)
        self.list71.setGeometry(QtCore.QRect(90, 130, 71, 192))
        self.list71.setObjectName("list71")
        self.list70 = QtWidgets.QListWidget(self.tab_4)
        self.list70.setGeometry(QtCore.QRect(20, 130, 71, 192))
        self.list70.setObjectName("list70")
        self.label_24 = QtWidgets.QLabel(self.tab_4)
        self.label_24.setGeometry(QtCore.QRect(160, 110, 71, 21))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(90, 110, 71, 21))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_4)
        self.label_26.setGeometry(QtCore.QRect(20, 110, 71, 21))
        self.label_26.setObjectName("label_26")
        self.satinal = QtWidgets.QPushButton(self.tab_4)
        self.satinal.setGeometry(QtCore.QRect(240, 190, 101, 71))
        self.satinal.setObjectName("satinal")
        self.label_27 = QtWidgets.QLabel(self.tab_4)
        self.label_27.setGeometry(QtCore.QRect(400, 50, 221, 31))
        self.label_27.setObjectName("label_27")
        self.HammaddeSelectAll = QtWidgets.QPushButton(self.tab_4)
        self.HammaddeSelectAll.setGeometry(QtCore.QRect(620, 50, 91, 31))
        self.HammaddeSelectAll.setObjectName("HammaddeSelectAll")
        self.list83 = QtWidgets.QListWidget(self.tab_4)
        self.list83.setGeometry(QtCore.QRect(610, 130, 71, 192))
        self.list83.setObjectName("list83")
        self.list82 = QtWidgets.QListWidget(self.tab_4)
        self.list82.setGeometry(QtCore.QRect(540, 130, 71, 192))
        self.list82.setObjectName("list82")
        self.list81 = QtWidgets.QListWidget(self.tab_4)
        self.list81.setGeometry(QtCore.QRect(470, 130, 71, 192))
        self.list81.setObjectName("list81")
        self.list80 = QtWidgets.QListWidget(self.tab_4)
        self.list80.setGeometry(QtCore.QRect(400, 130, 71, 192))
        self.list80.setObjectName("list80")
        self.label_28 = QtWidgets.QLabel(self.tab_4)
        self.label_28.setGeometry(QtCore.QRect(600, 110, 71, 21))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_4)
        self.label_29.setGeometry(QtCore.QRect(540, 110, 71, 21))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_4)
        self.label_30.setGeometry(QtCore.QRect(470, 110, 71, 21))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_4)
        self.label_31.setGeometry(QtCore.QRect(400, 110, 71, 21))
        self.label_31.setObjectName("label_31")
        self.hammaddeAlis_2 = QtWidgets.QLineEdit(self.tab_4)
        self.hammaddeAlis_2.setGeometry(QtCore.QRect(20, 60, 251, 41))
        self.hammaddeAlis_2.setObjectName("hammaddeAlis_2")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.list96 = QtWidgets.QListWidget(self.tab_5)
        self.list96.setGeometry(QtCore.QRect(380, 160, 71, 192))
        self.list96.setObjectName("list96")
        self.list90 = QtWidgets.QListWidget(self.tab_5)
        self.list90.setGeometry(QtCore.QRect(30, 160, 71, 192))
        self.list90.setObjectName("list90")
        self.list94 = QtWidgets.QListWidget(self.tab_5)
        self.list94.setGeometry(QtCore.QRect(310, 160, 71, 192))
        self.list94.setObjectName("list94")
        self.list93 = QtWidgets.QListWidget(self.tab_5)
        self.list93.setGeometry(QtCore.QRect(240, 160, 71, 192))
        self.list93.setObjectName("list93")
        self.list92 = QtWidgets.QListWidget(self.tab_5)
        self.list92.setGeometry(QtCore.QRect(170, 160, 71, 192))
        self.list92.setObjectName("list92")
        self.list91 = QtWidgets.QListWidget(self.tab_5)
        self.list91.setGeometry(QtCore.QRect(100, 160, 71, 192))
        self.list91.setObjectName("list91")
        self.label_32 = QtWidgets.QLabel(self.tab_5)
        self.label_32.setGeometry(QtCore.QRect(310, 140, 71, 21))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_5)
        self.label_33.setGeometry(QtCore.QRect(240, 140, 71, 21))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_5)
        self.label_34.setGeometry(QtCore.QRect(380, 140, 71, 21))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_5)
        self.label_35.setGeometry(QtCore.QRect(170, 140, 71, 21))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_5)
        self.label_36.setGeometry(QtCore.QRect(100, 140, 71, 21))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_5)
        self.label_37.setGeometry(QtCore.QRect(30, 140, 71, 21))
        self.label_37.setObjectName("label_37")
        self.karOrani = QtWidgets.QLineEdit(self.tab_5)
        self.karOrani.setGeometry(QtCore.QRect(30, 60, 211, 31))
        self.karOrani.setObjectName("karOrani")
        self.SatisSelectAll = QtWidgets.QPushButton(self.tab_5)
        self.SatisSelectAll.setGeometry(QtCore.QRect(500, 210, 151, 91))
        self.SatisSelectAll.setObjectName("SatisSelectAll")
        self.satisSelect_2 = QtWidgets.QLineEdit(self.tab_5)
        self.satisSelect_2.setGeometry(QtCore.QRect(30, 110, 211, 20))
        self.satisSelect_2.setObjectName("satisSelect_2")
        self.satisSelect = QtWidgets.QPushButton(self.tab_5)
        self.satisSelect.setGeometry(QtCore.QRect(250, 110, 75, 23))
        self.satisSelect.setObjectName("satisSelect")
        self.karUrunID = QtWidgets.QLineEdit(self.tab_5)
        self.karUrunID.setGeometry(QtCore.QRect(30, 29, 211, 31))
        self.karUrunID.setObjectName("karUrunID")
        self.Tedarikcifirmainsert_2 = QtWidgets.QPushButton(self.tab_5)
        self.Tedarikcifirmainsert_2.setGeometry(QtCore.QRect(250, 40, 111, 51))
        self.Tedarikcifirmainsert_2.setObjectName("Tedarikcifirmainsert_2")
        self.bildirim = QtWidgets.QListWidget(self.tab_5)
        self.bildirim.setGeometry(QtCore.QRect(30, 400, 321, 41))
        self.bildirim.setObjectName("bildirim")
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.Tedarikcifirmainsert.clicked.connect(self.tedarikciFirmaInsert)
        self.tedarikcifirmaselectall.clicked.connect(self.tedarikciFirmaSelectAll)
        self.tedarikcifirmaselect.clicked.connect(self.tedarikciFirmaSelect)
        self.tedarikciinsert.clicked.connect(self.TedarikciInsert)
        self.tedarikciselectall.clicked.connect(self.TedarikciSelectAll)
        self.musteriSelectAll.clicked.connect(self.MusteriselectA)
        self.musteriSelect.clicked.connect(self.Musteriselect)
        self.musteriInsert.clicked.connect(self.MusteriInsert)
        self.tedarikciselect.clicked.connect(self.tedarikciSelect)
        self.Uruninsert.clicked.connect(self.urunInsert)
        self.UrunSelectAll.clicked.connect(self.urunSelectAll)
        self.UrunSelect.clicked.connect(self.urunSelect)
        self.search.clicked.connect(self.searchHAMmadde)
        self.HammaddeSelectAll.clicked.connect(self.hammaddeSelectALL)
        self.satinal.clicked.connect(self.hammaddeSatinAl)
        self.Bileseninsert.clicked.connect(self.bilesenInsert)
        self.BilesenSelectAll.clicked.connect(self.bilesenSelectAll)
        self.BilesenSelect.clicked.connect(self.bilesenSelect)
        self.SatisSelectAll.clicked.connect(self.maliyetlerSelectAll)
        self.Tedarikcifirmainsert_2.clicked.connect(self.insertKar)
        self.satisSelect.clicked.connect(self.maliyetlerSelect)
        self.siparisInsert.clicked.connect(self.siparisinsert)
        self.siparisSelectAll.clicked.connect(self.siparisSelectALL)
        self.siparisSelect.clicked.connect(self.siparisSecme)
        veri.kargoMaliyetiHesaplama()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Urun ve Tedarikçi Ekleme</p></body></html>"))
        self.Uruninsert.setText(_translate("MainWindow", "İNSERT"))
        self.Bileseninsert.setText(_translate("MainWindow", "İNSERT"))
        self.urunstok.setText(_translate("MainWindow", "Stok Giriniz"))
        self.urunad.setText(_translate("MainWindow", "Ürün Adi Giriniz"))
        self.urunad2.setText(_translate("MainWindow", "Ürün Adi Giriniz"))
        self.uruntarih.setText(_translate("MainWindow", "Üretim Tarihi"))
        self.urunraf.setText(_translate("MainWindow", "Raf Ömrü"))
        self.bilesenad.setText(_translate("MainWindow", "Bileşen Adı Giriniz"))
        self.bilesenmiktar.setText(_translate("MainWindow", "Miktarını Giriniz"))
        self.UrunSelectAll.setText(_translate("MainWindow", "SELECT ALL"))
        self.UrunSelect.setText(_translate("MainWindow", "SELECT"))
        self.urunselect.setText(_translate("MainWindow", "Aramak istediğiniz ürün adını giriniz."))
        self.BilesenSelectAll.setText(_translate("MainWindow", "SELECT ALL"))
        self.bilesenselect.setText(_translate("MainWindow", "Aramak istediğiniz ürün adını giriniz."))
        self.BilesenSelect.setText(_translate("MainWindow", "SELECT"))
        self.label.setText(_translate("MainWindow", "    Ürün Adı"))
        self.label_2.setText(_translate("MainWindow", "    Raf Ömrü"))
        self.label_3.setText(_translate("MainWindow", "       Stok"))
        self.label_4.setText(_translate("MainWindow", " Üretim Tarihi"))
        self.label_5.setText(_translate("MainWindow", "    Ürün Adı"))
        self.label_6.setText(_translate("MainWindow", "    Bileşen Adı"))
        self.label_7.setText(_translate("MainWindow", "      Miktarı"))
        self.label_38.setText(_translate("MainWindow", "    Ürün ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Ürün Ekleme"))
        self.tedarikciFad.setText(_translate("MainWindow", "Firma Adını giriniz."))
        self.tedarikciFulke.setText(_translate("MainWindow", "Ülke giriniz."))
        self.tedarikciFsehir.setText(_translate("MainWindow", "Şehir giriniz."))
        self.Tedarikcifirmainsert.setText(_translate("MainWindow", "İNSERT"))
        self.tedarikcifirmaselectall.setText(_translate("MainWindow", "SELECT ALL"))
        self.tedarikciFselect.setText(_translate("MainWindow", "Aramak istediğiniz firma adını giriniz."))
        self.tedarikcifirmaselect.setText(_translate("MainWindow", "SELECT"))
        self.label_8.setText(_translate("MainWindow", "     FirmaIİD"))
        self.label_9.setText(_translate("MainWindow", "   Firma Adı"))
        self.label_10.setText(_translate("MainWindow", "        Ülke"))
        self.label_11.setText(_translate("MainWindow", "      Şehir"))
        self.tedarikciAd.setText(_translate("MainWindow", " Ürün adı giriniz."))
        self.TedarikciMiktar.setText(_translate("MainWindow", "Ürün Miktarı giriniz."))
        self.TedarikciUretim.setText(_translate("MainWindow", "Üretim Tarihi giriniz."))
        self.TedarikciRafomru.setText(_translate("MainWindow", "Raf Ömrü giriniz."))
        self.TedarikciSatis.setText(_translate("MainWindow", "Satış Fiyatı giriniz."))
        self.label_12.setText(_translate("MainWindow", "  Satış Fiyatı"))
        self.label_13.setText(_translate("MainWindow", "   Raf Ömrü"))
        self.label_14.setText(_translate("MainWindow", "  Üretim Tarihi"))
        self.label_15.setText(_translate("MainWindow", "  Ürün Miktarı"))
        self.label_16.setText(_translate("MainWindow", "    Ürün Adı"))
        self.tedarikciinsert.setText(_translate("MainWindow", "İNSERT"))
        self.tedarikciselectall.setText(_translate("MainWindow", "SELECT ALL"))
        self.tedarikciselect.setText(_translate("MainWindow", "SELECT"))
        self.TedarikciSelect.setText(_translate("MainWindow", "Aramak istediğiniz ürün adını giriniz."))
        self.label_23.setText(_translate("MainWindow", "    Firma ID"))
        self.TedarikiFirmaID.setText(_translate("MainWindow", "Firma ID giriniz."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tedarikçi Ekleme"))
        self.musteriAd.setText(_translate("MainWindow", "Müşteri Adı giriniz."))
        self.musteriSelectAll.setText(_translate("MainWindow", "SELECT ALL"))
        self.musteriSelect.setText(_translate("MainWindow", "SELECT"))
        self.musteriArama.setText(_translate("MainWindow", "Aramak istediginiz müşteri adini giriniz"))
        self.label_17.setText(_translate("MainWindow", "  Müşteri Adı"))
        self.label_18.setText(_translate("MainWindow", "   Müşteri İD"))
        self.siparisAdres.setText(_translate("MainWindow", "Adres giriniz."))
        self.siparisID.setText(_translate("MainWindow", "Müşteri ID giriniz."))
        self.siparisUrun.setText(_translate("MainWindow", "Talep Edilen Ürünü giriniz."))
        self.siparisMiktar.setText(_translate("MainWindow", "Miktar giriniz."))
        self.musteriInsert.setText(_translate("MainWindow", "İNSERT"))
        self.siparisInsert.setText(_translate("MainWindow", "İNSERT"))
        self.siparisSelectAll.setText(_translate("MainWindow", "SELECT ALL"))
        self.siparisArama.setText(_translate("MainWindow", "Aramak istediginiz müşteri id giriniz"))
        self.siparisSelect.setText(_translate("MainWindow", "SELECT"))
        self.label_19.setText(_translate("MainWindow", "   Müşteri İD"))
        self.label_20.setText(_translate("MainWindow", "     Adres"))
        self.label_21.setText(_translate("MainWindow", "       Ürün"))
        self.label_22.setText(_translate("MainWindow", "      Miktar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Müşteri Ekleme ve Sipariş"))
        self.hammaddeAlis.setText(_translate("MainWindow", "Satın almak istediğiniz hammadde adını giriniz."))
        self.search.setText(_translate("MainWindow", "Ara"))
        self.label_24.setText(_translate("MainWindow", "       Fiyatı"))
        self.label_25.setText(_translate("MainWindow", "       Miktarı"))
        self.label_26.setText(_translate("MainWindow", "Hammadde Adı"))
        self.satinal.setText(_translate("MainWindow", "En Ucuz \n"
" Olanı Satın Al"))
        self.label_27.setText(_translate("MainWindow", "Hammadde stoklarınızı görmek için tıklayınız."))
        self.HammaddeSelectAll.setText(_translate("MainWindow", "SELECT ALL"))
        self.label_28.setText(_translate("MainWindow", "         Stok "))
        self.label_29.setText(_translate("MainWindow", "    Alış Fiyatı"))
        self.label_30.setText(_translate("MainWindow", "Hammadde Adı"))
        self.label_31.setText(_translate("MainWindow", "     Firma Adı"))
        self.hammaddeAlis_2.setText(_translate("MainWindow", "Satın almak istediğiniz hammadde miktarini  giriniz."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Hammadde Satın Alma"))
        self.label_32.setText(_translate("MainWindow", "Toplam Maliyet"))
        self.label_33.setText(_translate("MainWindow", "    Kar Oranı"))
        self.label_34.setText(_translate("MainWindow", "   Satış Fiyatı"))
        self.label_35.setText(_translate("MainWindow", "    Hammadde "))
        self.label_36.setText(_translate("MainWindow", "        İşçilik"))
        self.label_37.setText(_translate("MainWindow", "     Ürün ID"))
        self.karOrani.setText(_translate("MainWindow", "Kar oranını giriniz."))
        self.SatisSelectAll.setText(_translate("MainWindow", "SELECT ALL"))
        self.satisSelect_2.setText(_translate("MainWindow", "Aramak istediğiniz ürün id giriniz."))
        self.satisSelect.setText(_translate("MainWindow", "SELECT"))
        self.karUrunID.setText(_translate("MainWindow", "Kar oranı girmek istediginiz urun id giriniz."))
        self.Tedarikcifirmainsert_2.setText(_translate("MainWindow", "İNSERT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Satış "))

    def tedarikciFirmaInsert(self):
        name = self.tedarikciFad.text()
        country = self.tedarikciFulke.text()
        city = self.tedarikciFsehir.text()
        veri.TedarikciFinsert(name, country, city)

    def tedarikciFirmaSelectAll(self):
        result = veri.TedarikciFSelectAll()
        k = 0
        self.List30.clear()
        self.List31.clear()
        self.List32.clear()
        self.List33.clear()

        for i in result:
            self.List30.addItem(str(result[k][0]))
            self.List31.addItem(str(result[k][1]))
            self.List32.addItem(str(result[k][2]))
            self.List33.addItem(str(result[k][3]))
            k = k + 1

    def tedarikciFirmaSelect(self):
        name = self.tedarikciFselect.text()
        result = veri.TedarikciFSelect(name)
        k = 0
        self.List30.clear()
        self.List31.clear()
        self.List32.clear()
        self.List33.clear()

        for i in result:
            self.List30.addItem(str(result[k][0]))
            self.List31.addItem(str(result[k][1]))
            self.List32.addItem(str(result[k][2]))
            self.List33.addItem(str(result[k][3]))
            k = k + 1

    def MusteriselectA(self):
        k = 0
        result = veri.MusteriselectAll()
        self.list50.clear()
        self.list51.clear()
        for i in result:
            self.list50.addItem(str((result[k][0])))
            self.list51.addItem(str(result[k][1]))
            k = k + 1

    def Musteriselect(self):
        k = 0
        name = self.musteriArama.text()
        result = veri.Musteriselect(name)
        self.list50.clear()
        self.list51.clear()
        for i in result:
            self.list50.addItem(str((result[k][0])))
            self.list51.addItem(str(result[k][1]))
            k = k + 1

    def MusteriInsert(self):
        name = self.musteriAd.text()
        veri.MusteriInsert(name)
        self.MusteriselectA()

    def TedarikciInsert(self):
        id = self.TedarikiFirmaID.text()
        name = self.tedarikciAd.text()
        miktar = self.TedarikciMiktar.text()
        uretimtarihi = self.TedarikciUretim.text()
        rafomru = self.TedarikciRafomru.text()
        satisfiyati = self.TedarikciSatis.text()
        veri.tedarikciInsert(id, name, miktar, uretimtarihi, rafomru, satisfiyati)

    def TedarikciSelectAll(self):
        k = 0
        result = veri.tedarikciSelectAll()
        self.List40.clear()
        self.List41.clear()
        self.List42.clear()
        self.List43.clear()
        self.List44.clear()
        self.List45.clear()
        for i in result:
            self.List40.addItem(str((result[k][0])))
            self.List41.addItem(str((result[k][1])))
            self.List42.addItem(str((result[k][2])))
            self.List43.addItem(str((result[k][3])))
            self.List44.addItem(str((result[k][4])))
            self.List45.addItem(str((result[k][5])))
            k = k + 1

    def tedarikciSelect(self):
        k = 0
        name = self.TedarikciSelect.text()
        result = veri.TedarikciSelect(name)
        self.List40.clear()
        self.List41.clear()
        self.List42.clear()
        self.List43.clear()
        self.List44.clear()
        self.List45.clear()
        for i in result:
            self.List40.addItem(str((result[k][0])))
            self.List41.addItem(str((result[k][1])))
            self.List42.addItem(str((result[k][2])))
            self.List43.addItem(str((result[k][3])))
            self.List44.addItem(str((result[k][4])))
            self.List45.addItem(str((result[k][5])))
            k = k + 1

    def urunInsert(self):
        self.hataEkrani.clear()
        name = self.urunad.text()
        stok = self.urunstok.text()
        tarih = self.uruntarih.text()
        rafOmru = self.urunraf.text()
        stok = int(stok)
        stokKontrol = []
        stokKontrol.clear()

        result = veri.bilesenSelect2(name)
        if (len(result) == 0):
            hata = ("Oncelikle urun bilesiklerini girmeniz gerekmektedir.")
            self.hataEkrani.setText(hata)
        else:
            for i in result:
                stokKontrol.append(veri.bilesenKontrol(i[1]))

            k = 0
            kontrol = True

            while (kontrol == True and len(stokKontrol) > k):
                print(result[k][2], stok, stokKontrol[k])

                if (result[k][2] * stok > stokKontrol[k]):
                    kontrol = False

                k = k + 1

            if (kontrol == True):

                id = veri.KimyasalUrunInsert(name)
                veri.gelistirilenUrunInsert(name, stok)
                veri.urunInsert(name, tarih, rafOmru, id, stok)

                for i in result:
                    veri.hammaddeDusme(i[1], i[2] * stok, id)

                veri.setIscilik(id, stok)

            else:
                error = ("Yeteri kadar hammadde bulunmamakta.Hammadde satin aliniz.")
                self.hataEkrani.setText(error)

    def bilesenSelectAll(self):
        result = veri.BilesenSelectAll()
        self.list20.clear()
        self.list21.clear()
        self.list22.clear()

        for i in result:
            self.list20.addItem((str(i[0])))
            self.list21.addItem((str(i[1])))
            self.list22.addItem((str(i[2])))

    def bilesenSelect(self):
        name = self.bilesenselect.text()
        result = veri.BilesenSelect(name)
        self.list20.clear()
        self.list21.clear()
        self.list22.clear()

        for i in result:
            self.list20.addItem((str(i[0])))
            self.list21.addItem((str(i[1])))
            self.list22.addItem((str(i[2])))

    def urunSelectAll(self):
        k = 0;
        result = veri.urunSelectAll()
        self.list10.clear()
        self.list11.clear()
        self.list12.clear()
        self.list13.clear()
        self.list13_2.clear()

        for i in result:
            self.list10.addItem((str(result[k][3])))
            self.list11.addItem((str(result[k][0])))
            self.list12.addItem((str(result[k][4])))
            self.list13.addItem((str(result[k][1])))
            self.list13_2.addItem((str(result[k][2])))
            k = k + 1

    def urunSelect(self):
        name = self.urunselect.text()
        k = 0;
        result = veri.urunSelect(name)
        self.list10.clear()
        self.list11.clear()
        self.list12.clear()
        self.list13.clear()

        for i in result:
            self.list10.addItem((str(result[k][0])))
            self.list11.addItem((str(result[k][4])))
            self.list12.addItem((str(result[k][1])))
            self.list13.addItem((str(result[k][2])))
            k = k + 1

    def bilesenInsert(self):
        name = self.urunad2.text()
        bilesen = self.bilesenad.text()
        miktar = self.bilesenmiktar.text()
        miktar = int(miktar)

        veri.bilesenInsert(name, bilesen, miktar)

    def hammaddeSatinAl(self):
        name = self.hammaddeAlis.text()
        stok = self.hammaddeAlis_2.text()
        stok = int(stok)
        k = 0

        # veri.kargoMaliyetiHesaplama()
        result1 = veri.tedarikciSelectAll2(name, stok)
        result2 = veri.parcaliSatinAlma(name, stok)

        print(result1[1])
        print(result2)
        if (result1[1] <= result2):
            print("toptan alinacak")
            veri.hammaddeSatinAl(result1[0], name, stok, result1[1])
        else:
            print("parcali alinacak")
            sonuc = veri.sonuc
            print(sonuc)
            for i in sonuc:
                veri.hammaddeSatinAl(i[0], name, i[2], i[1])
            veri.clearList()

    def searchHAMmadde(self):
        name = self.hammaddeAlis.text()
        result = veri.searchHammadde(name)
        k = 0

        self.list70.clear()
        self.list71.clear()
        self.list72.clear()

        for i in result:
            self.list70.addItem(name)
            self.list71.addItem(str(result[k][0]))
            self.list72.addItem(str(result[k][1]))
            k = k + 1

    def insertKar(self):
        id = self.karUrunID.text()
        id = int(id)
        kar = self.karOrani.text()
        result = veri.updateKar(kar, id)
        a="Satıştan birim başına"
        self.bildirim.addItem(a)
        self.bildirim.addItem(str(result))
        str2 = "TL kar edilecektir"
        self.bildirim.addItem(str(str2))



    def hammaddeSelectALL(self):
        k = 0
        result = veri.hammaddeSelectAll()

        self.list80.clear()
        self.list81.clear()
        self.list82.clear()
        self.list83.clear()

        for i in result:
            self.list80.addItem(str(result[k][0]))
            self.list81.addItem(str(result[k][1]))
            self.list82.addItem(str(result[k][4]))
            self.list83.addItem(str(result[k][2]))
            k = k + 1

    def maliyetlerSelectAll(self):
        result = veri.maliyetSelectAll()

        self.list90.clear()
        self.list91.clear()
        self.list92.clear()
        self.list93.clear()
        self.list94.clear()
        self.list96.clear()

        for i in result:
            self.list90.addItem(str(i[0]))
            self.list91.addItem(str(i[2]))
            self.list92.addItem(str(i[3]))
            self.list93.addItem(str(i[5]))
            self.list94.addItem(str(i[2]))
            self.list96.addItem(str(i[4]))

    def maliyetlerSelect(self):
        id = self.satisSelect_2.text()
        id = int(id)
        result = veri.SelectMaliyetler(id)
        self.list90.clear()
        self.list91.clear()
        self.list92.clear()
        self.list93.clear()
        self.list94.clear()
        self.list96.clear()

        for i in result:
            self.list90.addItem(str(i[0]))
            self.list91.addItem(str(i[1]))
            self.list92.addItem(str(i[3]))
            self.list93.addItem(str(i[5]))
            self.list94.addItem(str(i[2]))
            self.list96.addItem(str(i[4]))

    def siparisinsert(self):
        id = self.siparisID.text()
        id = int(id)
        adres = self.siparisAdres.text()
        talep = self.siparisUrun.text()
        miktar = self.siparisMiktar.text()
        miktar = int(miktar)
        result = veri.selectStok(talep)

        if (int(result[0]) == None):
            self.hataEkrani2.setText("Uzgunuz. Uretici firma böyle bir ürün üretmemekte.")
        elif (int(result[0]) < miktar):
            self.hataEkrani2.setText(
                "Uzgunuz. Stok eksikliğinden dolayı işleminiz gerçekleşmemekte. Kısa süre sonra tekrar deneyin.")
        elif (int(result[0]) >= miktar):
            self.hataEkrani2.setText("İsleminiz gerceklesmistir.")
            veri.insertSiparis(id, adres, talep, miktar)
            result2 = veri.selectMinFiyat(talep)
            k = 0
            while (miktar > 0):
                if (result2[k][1] > miktar):
                    veri.updateStok(result2[k][0], miktar)
                    miktar = 0
                else:
                    veri.updateStok(result2[k][0], result2[k][1])
                    miktar = miktar - result2[k][1]
                k = k + 1

    def siparisSelectALL(self):
        result=veri.siparisSelectAll()
        self.list61.clear()
        self.list62.clear()
        self.list63.clear()
        self.list64.clear()

        for i in result:
            self.list61.addItem(str(i[0]))
            self.list62.addItem(str(i[1]))
            self.list63.addItem(str(i[2]))
            self.list64.addItem(str(i[3]))

    def siparisSecme(self):
        id=self.siparisArama.text()
        result=veri.siparisSelect(id)
        self.list61.clear()
        self.list62.clear()
        self.list63.clear()
        self.list64.clear()
        for i in result:
            self.list61.addItem(str(i[0]))
            self.list62.addItem(str(i[1]))
            self.list63.addItem(str(i[2]))
            self.list64.addItem(str(i[3]))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

